---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    datacat: https://github.com/simp/puppet-datacat
    elasticsearch: https://github.com/simp/puppet-elasticsearch
    file_concat: https://github.com/simp/puppet-lib-file_concat
    grafana: https://github.com/simp/puppet-grafana
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    java: https://github.com/simp/puppetlabs-java
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    openldap: https://github.com/simp/pupmod-simp-openldap
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    rsync: https://github.com/simp/pupmod-simp-rsync
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simp: https://github.com/simp/pupmod-simp-simp
    simp_apache: https://github.com/simp/pupmod-simp-apache
    simp_elasticsearch: https://github.com/simp/pupmod-simp-simp_elasticsearch
    simpcat: https://github.com/simp/pupmod-simp-concat
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    simp_grafana: "#{source_dir}"
